layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

# specialties      
savoirs:
  - name: Java EE
    web_url: https://github.com/topics/java
    image_url: https://p7.hiclipart.com/preview/405/878/407/java-runtime-environment-computer-icons-java-platform-standard-edition-java.jpg

  - name: Weblogic
    web_url: https://github.com/topics/weblogic

  - name: Web services
    web_url: https://github.com/topics/rest

  - name: Jetty
    web_url: https://github.com/topics/jetty

  - name: Apache Ant
    web_url: https://github.com/topics/jetty

  - name: Angular / Typescript
    web_url: https://github.com/topics/angular

  

    
topics:
  - name: JavaScript
    web_url: https://github.com/topics/javascript

  - name: Machine Learning
  
  - name: CSS
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png

  - name: Functional Programming

  - name: Scala

  - name: Docker

  - name: Mobile development
    web_url: https://github.com/topics/sass
    
  - name: Spring