layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"


# main skills / specialties
savoirs:
  - name: Java EE
    web_url: https://github.com/topics/java
    image_url: https://seeklogo.com/images/J/java-logo-41D4155FC3-seeklogo.com.png

  - name: Weblogic
    web_url: https://www.oracle.com/middleware/WebLogic/
    image_url: https://esolution.ca/wp-content/uploads/oracle_fusion_middleware_weblogic_server.png

  - name: Web services
    web_url: https://github.com/topics/rest
    image_url: https://dzone.com/storage/temp/4801535-rest-api.jpg

  - name: Jetty
    web_url: https://www.eclipse.org/jetty/
    image_url: https://www.eclipse.org/jetty/images/jetty-logo-80x22.png

  - name: Angular / Typescript
    web_url: https://github.com/topics/angular
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/angular/angular.png

  - name: Apache Ant
    web_url: https://ant.apache.org/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Apache-Ant-logo.svg/1200px-Apache-Ant-logo.svg.png

# other interests
topics:
  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png

  - name: Machine Learning

  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://www.pnglot.com/pngfile/detail/504-5048887_cascading-style-sheets-logo-html-blue-text-png.png

  - name: Functional Programming

  - name: Scala
    web_url: https://github.com/topics/scala
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/scala/scala.png

  - name: Mobile development
    web_url: https://github.com/topics/mobile

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png

  - name: Spring Boot
    web_url: https://github.com/topics/springboot
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/spring-boot/spring-boot.png



projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username


